name: Update README and VectorStore embeddings on push to main

on:
  push:
    branches:
      - master

jobs:
  # TODO: reddit links responds 403 status, can't able to use config file in link checker
  # markdown-link-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - uses: gaurav-nelson/github-action-markdown-link-check@v1
  #   with:
  #       use-quiet-mode: 'yes'

  update-readme-and-embeddings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Readme generation script
        run: python scripts/generate_readme.py

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
      
      - name: Run Update Embeddings script
        run: uv run python scripts/update_embeddings.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        working-directory: chatbot/server

      - name: Check for changes
        id: git-diff
        run: echo "::set-output name=changes::$(git diff --exit-code > /dev/null && echo 'false' || echo 'true')"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update README and Embeddings via GitHub Action"
          git push
        if: steps.git-diff.outputs.changes == 'true'