name: Update README on push to main

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python scripts/generate_readme.py
